name: "Tandoor Recipes"
description: "Run the latest stable version of Tandoor Recipes"
url: "https://tandoor.dev"

slug: "tandoor"

startup: application
boot: auto
init: false
backup: cold

arch:
  - amd64
  - arm64

ports:
  8080/tcp: null

ports_description:
  8080/tcp: Web Interface

webui: "http://[HOST]:[PORT:8080]"

image: ghcr.io/tandoorrecipes/recipes
version: 2.5.3

map:
  - type: data
    read_only: false
    path: /opt/recipes

schema:
  secret_key: "password"
  allowed_hosts: "str"
  enable_signup: "list(0|1)"
  timezone: "str"
  email_host: "str?"
  email_port: "int?"
  email_user: "str?"
  email_password: "password?"
  email_use_tls: "list(0|1)?"
  default_from_email: "str?"

options:
  enable_signup: 1
  timezone: "Etc/UTC"

environment:
  DB_ENGINE: "django.db.backends.sqlite3"
  SECRET_KEY: "{secret_key}"
  ALLOWED_HOSTS: "{allowed_hosts}"
  ENABLE_SIGNUP: "{enable_signup}"
  TZ: "{timezone}"
  EMAIL_HOST: "{email_host}"
  EMAIL_PORT: "{email_port}"
  EMAIL_HOST_USER: "{email_host_user}"
  EMAIL_HOST_PASSWORD: "{email_host_password}"
  EMAIL_USE_TLS: "{email_use_tls}"
  DEFAULT_FROM_EMAIL: "{default_from_email}"
